fix: resolve linting issue
Error: cmd/use_correct_pm.go:20:12: unused-parameter: parameter 'cmd' seems to be unused, consider
removing or renaming it as _ (revive)
Run: func(cmd *cobra.Command, args []string) {
^
level=warning msg="[config_reader] The configuration option `linters.errcheck.ignore`
is deprecated, please use `linters.errcheck.exclude-functions`."